### ISSUE TITLE
Invalid import assertion

### ISSUE THREAD

**Issue by nicolo-ribaudo** [AcronixBot/acronix-nintendo-helpers#1]
Hi!

I noticed that you are using an `integrity` assertion (https://github.com/AcronixBot/acronix-nintendo-helpers/blob/351b1040eb6cae9258c6a344fd79e9d3d80da075/src/WebService.ts#L7), that is invalid and it's currently being ignored by browsers.

We are updating the import assertions behavior to throw on unknown ones, so you might want to remove it.

**Comment by Voroniyx** [comment]
Hey,
thank you for the hint, ill take a look into it and remove it later.

**Comment by Voroniyx** [comment]
The Commit [add0893](https://github.com/AcronixBot/acronix-nintendo-helpers/commit/add08933aa92eb484a8f1d92ebd6e5b2b90ba6d2) should solve the issue
